# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd99214e4ea25ff3e82f2b94985bce86fb82c0386cb3d87ab06dec9531016bee1b03436678f7cfea91b510f82f8eec1d0b8c7a4fb8d9150be8e8b879a4c7add6

test:
  secret_key_base: fb4bb35d8cde4dd0b4972f54c8fb7fc165c109ee05f941aa0ec004452600c68d9d3b70fe6c9b784ea38edbaf57e7a439faf35e7e82ca15fc8595fd3e05ae3b88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
